server:
  port: 9100

spring:
  application:
    name: config-server
  cloud:
    config:
      server:
        git:
          uri: #ssh认证方式
          ignore-local-ssh-settings: true
          private-key: |
            -----BEGIN RSA PRIVATE KEY-----
            <your private key>
            -----END RSA PRIVATE KEY-----

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
